import React, { useState } from "react";

const packersAndMoversData = [
  {
    state: "Andhra Pradesh",
    cities: [
      "Amaravati",
      "Anantapur",
      "Chittoor",
      "Guntur",
      "Kadapa (Cuddapah)",
      "Kakinada",
      "Kurnool",
      "Nellore",
      "Ongole",
      "Rajahmundry",
      "Srikakulam",
      "Tirupati",
      "Vijayawada",
      "Visakhapatnam",
      "Vizianagaram"
    ]
  },
  {
    state: "Arunachal Pradesh",
    cities: [
      "Itanagar",
      "Naharlagun",
      "Tawang",
      "Bomdila",
      "Ziro",
      "Pasighat",
      "Roing",
      "Tezu",
      "Aalo (Along)",
      "Basar",
      "Yingkiong",
      "Seppa",
      "Anini",
      "Khonsa",
      "Changlang",
      "Daporijo",
      "Mechuka",
      "Jairampur",
      "Namsai",
      "Tirap"
    ]
  },
  {
    state: "Assam",
    cities: [
      "Guwahati",
      "Dibrugarh",
      "Silchar",
      "Jorhat",
      "Tinsukia",
      "Nagaon",
      "Bongaigaon",
      "Tezpur",
      "Barpeta",
      "Sivasagar",
      "Haflong",
      "Goalpara",
      "Karimganj",
      "Diphu",
      "Nalbari",
      "Morigaon",
      "Chirang",
      "Majuli",
      "Darrang",
      "Sonitpur"
    ]
  },
  {
    state: "Bihar",
    cities: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Munger",
      "Purnia",
      "Darbhanga",
      "Buxar",
      "Chapra",
      "Saharsa",
      "Siwan",
      "Nalanda",
      "Kishanganj",
      "Bagaha",
      "Raxaul",
      "Chhapra",
      "Arrah",
      "Hajipur",
      "Motihari",
      "Samastipur",
      "Jamui",
      "Sitamarhi",
      "Lakhisarai",
      "Katihar",
      "Banka",
      "Bhabhua",
      "Supaul",
      "Gopalganj"
    ]
  },
  {
    state: "Chhattisgarh",
    cities: [
      "Raipur",
      "Bhilai",
      "Korba",
      "Bilaspur",
      "Durg",
      "Raigarh",
      "Jagdalpur",
      "Rajnandgaon",
      "Ambikapur",
      "Dhamtari",
      "Mungeli",
      "Kanker",
      "Bastar",
      "Janjgir-Champa"
    ]
  },
  {
    state: "Goa",
    cities: [
      "Panaji",
      "Vasco da Gama",
      "Margao",
      "Mapusa",
      "Ponda",
      "Curchorem",
      "Quepem",
      "Bicholim",
      "Sanquelim",
      "Dona Paula",
      "Old Goa",
      "Canacona",
      "Verna",
      "Colva",
      "Betul"
    ]
  },
  {
    state: "Gujarat",
    cities: [
      "Ahmedabad",
      "Vadodara",
      "Surat",
      "Rajkot",
      "Bhavnagar",
      "Junagadh",
      "Jamnagar",
      "Gandhinagar",
      "Anand",
      "Vapi",
      "Nadiad",
      "Mehsana",
      "Navsari",
      "Valsad",
      "Bharuch",
      "Morbi",
      "Surendranagar",
      "Porbandar",
      "Patan",
      "Daman",
      "Rajpipla",
      "Himatnagar",
      "Kutch",
      "Banaskantha",
      "Palanpur"
    ]
  },
  {
    state: "Haryana",
    cities: [
      "Ambala",
      "Bhiwani",
      "Faridabad",
      "Fatehabad",
      "Gurugram (Gurgaon)",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Mewat",
      "Palwal",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamunanagar"
    ]
  },
  {
    state: "Himachal Pradesh",
    cities: [
      "Shimla",
      "Manali",
      "Kullu",
      "Dharamshala",
      "Solan",
      "Kangra",
      "Mandi",
      "Bilaspur",
      "Hamirpur",
      "Una",
      "Nahan",
      "Palampur",
      "Chamba",
      "Reckong Peo",
      "Chandigarh"
    ]
  },
  {
    state: "Jharkhand",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro Steel City",
      "Deoghar",
      "Hazaribagh",
      "Giridih",
      "Dumka",
      "Chaibasa",
      "Ramgarh",
      "Madhupur",
      "Khunti",
      "Sahebganj",
      "Simdega",
      "Latehar",
      "Palamu",
      "Koderma",
      "West Singhbhum",
      "Pakur"
    ]
  },
  {
    state: "Karnataka",
    cities: [
      "Bengaluru (Bangalore)",
      "Mysuru (Mysore)",
      "Hubballi (Hubli)",
      "Dharwad",
      "Mangalore",
      "Belagavi (Belgaum)",
      "Udupi",
      "Shimoga (Shivamogga)",
      "Tumakuru (Tumkur)",
      "Chitradurga",
      "Bagalkot",
      "Hassan",
      "Davangere",
      "Gulbarga (Kalaburagi)",
      "Bellary (Ballari)",
      "Bijapur (Vijayapura)",
      "Chikkamagaluru (Chikmagalur)",
      "Kolar",
      "Raichur",
      "Sagar",
      "Mandya",
      "Karwar",
      "Koppal",
      "Ramanagaram",
      "Yadgir"
    ]
  },
  {
    state: "Kerala",
    cities: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Thrissur",
      "Malappuram",
      "Kottayam",
      "Palakkad",
      "Kollam",
      "Kannur",
      "Pathanamthitta",
      "Idukki",
      "Ernakulam",
      "Wayanad",
      "Alappuzha",
      "Kasaragod",
      "Attingal",
      "Changanassery",
      "Punalur",
      "Varkala",
      "Ottappalam"
    ]
  },
  {
    state: "Madhya Pradesh",
    cities: [
      "Bhopal",
      "Indore",
      "Gwalior",
      "Jabalpur",
      "Ujjain",
      "Sagar",
      "Rewa",
      "Ratlam",
      "Satna",
      "Dewas",
      "Khandwa",
      "Chhindwara",
      "Burhanpur",
      "Shivpuri",
      "Sehore",
      "Hoshangabad",
      "Guna",
      "Tikamgarh",
      "Mandsaur",
      "Neemuch",
      "Vidisha",
      "Rajgarh",
      "Chhatarpur",
      "Shahdol",
      "Pachmarhi"
    ]
  },
  {
    state: "Maharashtra",
    cities: [
      "Pune",
      "Nagpur",
      "Nashik",
      "Aurangabad",
      "Thane",
      "Solapur",
      "Satara",
      "Kolhapur",
      "Chandrapur",
      "Amravati",
      "Jalgaon",
      "Nanded",
      "Akola",
      "Dhule",
      "Latur",
      "Parbhani",
      "Yavatmal",
      "Ratnagiri",
      "Sindhudurg",
      "Wardha",
      "Bhandara",
      "Kalyan",
      "Vasai-Virar",
      "Khamgaon",
      "Panvel",
      "Shirdi",
      "Karad",
      "Sangli",
      "Chiplun",
      "Malvan",
      "Baramati",
      "Bhivandi",
      "Talegaon Dabhade",
      "Junnar",
      "Buldhana",
      "Akola",
      "Gadchiroli"
    ]
  },
  {
    state: "Manipur",
    cities: [
      "Imphal",
      "Churachandpur",
      "Thoubal",
      "Kakching",
      "Jiribam",
      "Ukhrul",
      "Senapati",
      "Tamenglong",
      "Bishnupur",
      "Moreh"
    ]
  },
  {
    state: "Meghalaya",
    cities: [
      "Shillong",
      "Tura",
      "Nongpoh",
      "Jowai",
      "Williamnagar",
      "Mawlai",
      "Baghmara",
      "Resubelpara",
      "Cherrapunji",
      "Pynursla"
    ]
  },
  {
    state: "Mizoram",
    cities: [
      "Aizawl",
      "Lunglei",
      "Champhai",
      "Saitual",
      "Kolasib",
      "Mamit",
      "Serchhip",
      "Lawngtlai",
      "Hnahthial",
      "Bairabi"
    ]
  },
  {
    state: "Nagaland",
    cities: [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Mon",
      "Wokha",
      "Zunheboto",
      "Kiphire",
      "Phek",
      "Tuensang",
      "Longleng"
    ]
  },
  {
    state: "Odisha",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Puri",
      "Berhampur",
      "Sambalpur",
      "Balasore",
      "Koraput",
      "Jharsuguda",
      "Baripada",
      "Kendrapara",
      "Bargarh",
      "Nayagarh",
      "Angul",
      "Dhenkanal",
      "Bhadrak",
      "Jajpur",
      "Rayagada",
      "Kalahandi",
      "Ganjam",
      "Chandbali",
      "Phulbani",
      "Jeypore",
      "Sundargarh"
    ]
  },
  {
    state: "Punjab",
    cities: [
      "Amritsar",
      "Ludhiana",
      "Chandigarh",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Mohali",
      "Moga",
      "Hoshiarpur",
      "Rupnagar (Ropar)",
      "Fatehgarh Sahib",
      "Gurdaspur",
      "Sri Muktsar Sahib",
      "Faridkot",
      "Tarn Taran",
      "Kapurthala",
      "Zirakpur",
      "Nawanshahr",
      "Sangrur",
      "Firozpur",
      "Barnala",
      "Pathankot"
    ]
  },
  {
    state: "Rajasthan",
    cities: [
      "Ajmer",
      "Alwar",
      "Bikaner",
      "Chittorgarh",
      "Jaipur",
      "Jaisalmer",
      "Jodhpur",
      "Kota",
      "Udaipur",
      "Bhilwara",
      "Sikar",
      "Pali",
      "Barmer",
      "Banswara",
      "Churu",
      "Dungarpur",
      "Hanumangarh",
      "Jhalawar",
      "Nagaur",
      "Pratapgarh",
      "Rajsamand",
      "Sawai Madhopur",
      "Tonk",
      "Rishabhdev",
      "Rajapark"
    ]
  },
  {
    state: "Sikkim",
    cities: [
      "Gangtok",
      "Namchi",
      "Pelling",
      "Mangan",
      "Rangpo",
      "Jorethang",
      "Singhik",
      "Geyzing",
      "Yuksom",
      "Ravangla"
    ]
  },
  {
    state: "Tamil Nadu",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Erode",
      "Vellore",
      "Tiruppur",
      "Thanjavur",
      "Dindigul",
      "Nagercoil",
      "Kanchipuram",
      "Cuddalore",
      "Karur",
      "Namakkal",
      "Virudhunagar",
      "Chidambaram",
      "Karaikudi",
      "Sivakasi",
      "Pollachi",
      "Kanyakumari",
      "Ranipet",
      "Tiruvarur",
      "Pudukkottai",
      "Dharmapuri",
      "Krishnagiri",
      "Ariyalur",
      "Nagapattinam",
      "Theni"
    ]
  },
  {
    state: "Telangana",
    cities: [
      "Hyderabad",
      "Warangal",
      "Khammam",
      "Nizamabad",
      "Karimnagar",
      "Ramagundam",
      "Mahabubnagar",
      "Nalgonda",
      "Adilabad",
      "Miryalaguda",
      "Suryapet",
      "Jagtial",
      "Kothagudem",
      "Mancherial",
      "Bhongir",
      "Peddapalli",
      "Medak",
      "Zaheerabad",
      "Sangareddy",
      "Tandur"
    ]
  },
  {
    state: "Tripura",
    cities: [
      "Agartala",
      "Belonia",
      "Dharmanagar",
      "Kailashahar",
      "Udaipur",
      "Ambassa",
      "Sepahijala",
      "Jirania",
      "Mohanpur",
      "Ranir Bazar"
    ]
  },
  {
    state: "Uttar Pradesh",
    cities: [
      "Agra",
      "Aligarh",
      "Allahabad (Prayagraj)",
      "Amroha",
      "Ayodhya (Faizabad)",
      "Azamgarh",
      "Barabanki",
      "Bareilly",
      "Bijnor",
      "Bulandshahr",
      "Chandauli",
      "Etawah",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Ghaziabad",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hardoi",
      "Hathras",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur",
      "Kasganj",
      "Kaushambi",
      "Kushinagar",
      "Lakhimpur Kheri",
      "Lucknow",
      "Mathura",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Noida",
      "Raebareli",
      "Rampur",
      "Saharanpur",
      "Sambhal",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi"
    ]
  },
  {
    state: "Uttarakhand",
    cities: [
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Rishikesh",
      "Roorkee",
      "Haldwani",
      "Kashipur",
      "Udham Singh Nagar",
      "Pantnagar",
      "Ramnagar",
      "Mussoorie",
      "Pauri",
      "Almora",
      "Bageshwar",
      "Tehri",
      "Rudraprayag",
      "Chamoli",
      "Kedarnath",
      "Badrinath"
    ]
  },
  {
    state: "West Bengal",
    cities: [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Bardhaman",
      "Malda",
      "Jalpaiguri",
      "Bikaner",
      "Kurseong",
      "Balurghat",
      "Murshidabad",
      "Kolar",
      "Sunderbans",
      "Raniganj",
      "Haldia",
      "Midnapore",
      "Hooghly",
      "Shibpur",
      "Cooch Behar",
      "Bankura",
      "Purulia",
      "Darjeeling",
      "Bongaon",
      "Berhampore"
    ]
  }
];

const packersAndMoversKeywords = [
  "movers and packers malad west", "Movers and Packers in dahisar", "Movers and Packers in borivali", "Movers and Packers in bandra", "Movers and Packers in andheri", "Movers and Packers in dadar", 
  "packers and movers in malad", "movers and packers malad east", "packers and movers malad east", "movers and packers mumbai malad west", "packers and movers in mumbai malad east", 
  "Packers and Movers", "home shifting", "packers and movers near me", "house shifting services near me", "house shifting services", "international movers and packers", 
  "home shifting services", "packers for moving", "professional packers", "moving packers near me", "packers and movers cost", "packers and movers near me with price", 
  "interstate movers and packers", "professional movers and packers", "best packers and movers", "movers and packers price", "cheap movers and packers near me", 
  "local packers and movers", "home movers and packers", "professional packing services", "moving packing services", "house moving companies near me", "household shifting services near me", 
  "house shifting near me", "home shifting packers and movers near me", "home shifting transport near me", "packers and movers for house shifting near me", 
  "transport for shifting house near me", "local shifting near me", "long distance movers and packers", "best packers and movers for interstate", 
  "interstate movers and packers near me", "Affordable Packers and Movers", "Packers and Movers Services", "Cheap Packers and Movers", "Reliable Packers and Movers", 
  "Professional Packers and Movers", "Experienced Packers and Movers", "Local Packers and Movers", "Interstate Packers and Movers", "Movers and Packers", 
  "Movers and Packers Near Me", "Moving Services", "Best Moving Companies", "Home Shifting Services", "Office Shifting Services", "Affordable Moving Companies", 
  "Packers and Movers Rates", "local movers", "moving companies", "moving service", "movers near me", "long distance moving companies", "piano movers near me", 
  "piano movers", "cheap movers near me", "local movers near me", "furniture movers", "long distance movers", "furniture movers near me", "local moving companies", 
  "pool table movers", "moving and storage companies", "moving help near me", "house movers", "packers movers", "interstate moving companies", 
  "short distance movers near me", "moving services near me", "house removals", "cheap moving companies", "professional movers", "house movers near me", 
  "cheap movers", "pool table movers near me", "super movers", "long distance movers near me", "local moving companies near me", "best long distance moving companies", 
  "moving and storage", "out of state moving companies", "Packers and Movers in Mumbai", "Packers and Movers Reviews", "Packers and Movers with Insurance", 
  "Moving and Storage Services", "Moving Services in Mumbai", "Moving Quotes", "Best Moving Services for Apartments", "Packers and Movers Cost Estimate", 
  "House Shifting Services", "Office Relocation Services", "Furniture Moving Services", "Bike Transport Services", "Car Transport Services", 
  "Vehicle Relocation Services", "Furniture Relocation Services", "Packing and Unpacking Services", "Storage and Moving Solutions", "International Moving Services", 
  "Warehouse Shifting Services", "Long-Distance Moving Services", "Domestic Relocation Services", "Pet Relocation Services", "Corporate Relocation Services", 
  "Industrial Relocation Services", "Specialized Moving Services for Fragile Items", "Packing Supplies and Services", "Loading and Unloading Services", 
  "Furniture Dismantling and Assembling Services", "Local Movers in Mumbai", "Packers and Movers Mumbai", "Top Movers in Mumbai", "Movers and Packers in Mumbai", 
  "Packers and Movers for Mumbai", "Best Moving Services in Mumbai", "Affordable Moving Companies in Mumbai", "Household Shifting in Mumbai", 
  "Office Shifting in Mumbai", "Home Relocation Services", "Corporate Shifting Solutions", "Relocation Services for Offices", "Moving Services for Large Houses", 
  "Car Carrier Services", "Bike Transport from Mumbai to Pune", "Furniture Transport Solutions", "Moving from Mumbai to Pune", "Affordable Home Movers", 
  "Relocation Services for Commercial Spaces", "Quick Packers and Movers", "Emergency Relocation Services", "Packers and Movers for International Shipping", 
  "Professional Home Shifting Services", "Best Packing Services for Moving", "Top Moving Services for Office", "Movers for Large Furniture", 
  "Household Moving Company", "Packers and Movers for Heavy Items", "Packers and Movers for Fragile Goods", "Loading and Unloading Services for Moving", 
  "Unpacking Services after Moving", "Best Packers and Movers for Long Distance", "Packing and Unpacking Moving Services", "Professional Furniture Movers", 
  "Vehicle Transport Companies", "Storage Solutions for Moving", "Temporary Storage for Relocation", "Moving Truck Rentals", "Loading and Unloading Experts", 
  "Dismantling and Reassembly of Furniture", "Office Moving Solutions", "Residential Shifting Solutions", "Relocation and Transport Services", 
  "Piano Moving Services", "How much do Packers and Movers cost?", "How to choose the best Packers and Movers?", "What services do Packers and Movers offer?", 
  "Tips for packing while moving", "How long does moving take?", "What should I look for in a moving company?", "Packers and Movers price list", 
  "Benefits of hiring professional movers", "Is insurance necessary for moving?", "How to prepare for office relocation?", "best moving companies in Mumbai", 
  "Mumbai long distance movers", "pool table moving company", "cheap piano movers", "commercial movers", "residential movers", "moving and storage services", 
  "senior movers", "office moving company", "apartment movers", "international moving services", "stuff to know about a place before you move to Mumbai", 
  "best way to pack a moving truck", "hot tub mover", "reputable moving company", "packing plants for moving", "pet moving company", "cheapest cross country movers", 
  "budget truck rental near me", "local moving services", "movers quote", "how to move a sectional sofa/couch", "mobile home movers", "moving and storage service", 
  "moving company reviews", "small moving companies", "family moving company", "same-day moving", "emergency relocation", "moving company military families", 
  "short-distance movers", "large office moving company", "eco-friendly movers", "moving companies with full value insurance", "affordable storage unit", 
  "common moving scams", "best Mumbai neighborhoods", "relocation realtor in Mumbai", "apartments in Mumbai", "climate-controlled move and storage", 
  "cheap packing and unpacking services", "corporate relocation movers", "antique furniture movers"
];

const acServiceKeywords = [
  "ac washing service near me", "z wash ac service", "AC repair", "Air conditioning repair", "AC service", "HVAC repair",
  "Air conditioner service", "ac repair near me", "air conditioner repair", "ac service near me",
  "hvac repair near me", "hvac service near me", "hvac companies near me", "air conditioner repair near me",
  "hvac repair", "air conditioning service near me", "ac companies near me", "ac tune up near me",
  "ac technician near me", "ac maintenance near me", "emergency ac repair near me", "hvac maintenance near me",
  "commercial hvac companies near me", "emergency ac service", "ac tune up cost", "hvac installers near me",
  "heat repair near me", "hvac technician near me", "ac fix near me", "aircon servicing", "same day ac repair",
  "ac companies", "24 hour ac repair near me", "best hvac companies near me", "affordable hvac repair near me",
  "24 hour ac service", "emergency air conditioner repair", "ac unit repair near me", "heating and air repair near me",
  "air conditioner maintenance near me", "air conditioner installation near me", "24 7 ac repair",
  "emergency air conditioning", "emergency hvac service", "heating and cooling repair near me",
  "emergency air conditioning service", "ac unit central air conditioner repair", "air conditioning installation",
  "ac fix", "24 hour air conditioning service", "furnace repair near me", "ac repair cost",
  "best ac repair near me", "AC maintenance", "Air conditioner maintenance", "AC maintenance near me",
  "Air conditioner maintenance near me", "AC tune-up", "AC tune-up near me", "AC rental",
  "Air conditioner rental", "AC on rent", "AC rental services", "Portable AC rental", "Window AC rental",
  "AC AMC services", "Air conditioner AMC", "AC annual maintenance contract", "HVAC AMC services",
  "AC maintenance contract", "Emergency AC repair", "AC repair services", "AC deep cleaning",
  "Air conditioner deep cleaning", "AC anti-rust treatment", "AC coil cleaning", "AC chemical cleaning",
  "AC rust prevention service", "AC gas filling", "Air conditioner gas refill", "AC refrigerant recharge",
  "AC gas top-up", "AC freon refill", "AC gas filling near me", "Air conditioner repair service",
  "Emergency AC repair near me", "Mumbai air conditioning repair", "AC service in Mumbai",
  "Best AC technicians in Mumbai", "air services in Mumbai", "Affordable AC maintenance in Mumbai",
  "Emergency AC repair in Mumbai", "Virar air conditioning repair", "AC service in Virar",
  "Best AC technicians in Virar", "air services in Virar", "Affordable AC maintenance in Virar",
  "Emergency AC repair in Virar", "Vasai air conditioning repair", "AC service in Vasai",
  "Best AC technicians in Vasai", "air services in Vasai", "Affordable AC maintenance in Vasai",
  "Emergency AC repair in Vasai", "Mira Road air conditioning repair", "AC service in Mira Road",
  "Best AC technicians in Mira Road", "air services in Mira Road", "Affordable AC maintenance in Mira Road",
  "Emergency AC repair in Mira Road", "Nala Sopara air conditioning repair", "AC service in Nala Sopara",
  "Best AC technicians in Nala Sopara", "air services in Nala Sopara", "Affordable AC maintenance in Nala Sopara",
  "Emergency AC repair in Nala Sopara", "Bhayandar air conditioning repair", "AC service in Bhayandar",
  "Best AC technicians in Bhayandar", "air services in Bhayandar", "Affordable AC maintenance in Bhayandar",
  "Emergency AC repair in Bhayandar", "Naigaon air conditioning repair", "AC service in Naigaon",
  "Best AC technicians in Naigaon", "air services in Naigaon", "Affordable AC maintenance in Naigaon",
  "Emergency AC repair in Naigaon", "Dahisar air conditioning repair", "AC service in Dahisar",
  "Best AC technicians in Dahisar", "air services in Dahisar", "Affordable AC maintenance in Dahisar",
  "Emergency AC repair in Dahisar", "Borivali air conditioning repair", "AC service in Borivali",
  "Best AC technicians in Borivali", "air services in Borivali", "Affordable AC maintenance in Borivali",
  "Emergency AC repair in Borivali", "Kandivali air conditioning repair", "AC service in Kandivali",
  "Best AC technicians in Kandivali", "air services in Kandivali", "Affordable AC maintenance in Kandivali",
  "Emergency AC repair in Kandivali", "Malad air conditioning repair", "AC service in Malad",
  "Best AC technicians in Malad", "air services in Malad", "Affordable AC maintenance in Malad",
  "Emergency AC repair in Malad", "Goregaon air conditioning repair", "AC service in Goregaon",
  "Best AC technicians in Goregaon", "air services in Goregaon", "Affordable AC maintenance in Goregaon",
  "Emergency AC repair in Goregaon", "Jogeshwari air conditioning repair", "AC service in Jogeshwari",
  "Best AC technicians in Jogeshwari", "air services in Jogeshwari", "Affordable AC maintenance in Jogeshwari",
  "Emergency AC repair in Jogeshwari", "Andheri air conditioning repair", "AC service in Andheri",
  "Best AC technicians in Andheri", "air services in Andheri", "Affordable AC maintenance in Andheri",
  "Emergency AC repair in Andheri", "Ville Parle air conditioning repair", "AC service in Ville Parle",
  "Best AC technicians in Ville Parle", "air services in Ville Parle", "Affordable AC maintenance in Ville Parle",
  "Emergency AC repair in Ville Parle", "Santacruz air conditioning repair", "AC service in Santacruz",
  "Best AC technicians in Santacruz", "air services in Santacruz", "Affordable AC maintenance in Santacruz",
  "Emergency AC repair in Santacruz", "Khar Road air conditioning repair", "AC service in Khar Road",
  "Best AC technicians in Khar Road", "air services in Khar Road", "Affordable AC maintenance in Khar Road",
  "Emergency AC repair in Khar Road", "Bandra air conditioning repair", "AC service in Bandra",
  "Best AC technicians in Bandra", "air services in Bandra", "Affordable AC maintenance in Bandra",
  "Emergency AC repair in Bandra", "Mahim air conditioning repair", "AC service in Mahim",
  "Best AC technicians in Mahim", "air services in Mahim", "Affordable AC maintenance in Mahim",
  "Emergency AC repair in Mahim", "Matunga air conditioning repair", "AC service in Matunga",
  "Best AC technicians in Matunga", "air services in Matunga", "Affordable AC maintenance in Matunga",
  "Emergency AC repair in Matunga", "Dadar air conditioning repair", "AC service in Dadar",
  "Best AC technicians in Dadar", "air services in Dadar", "Affordable AC maintenance in Dadar",
  "Emergency AC repair in Dadar", "Prabhadevi air conditioning repair", "AC service in Prabhadevi",
  "Best AC technicians in Prabhadevi", "air services in Prabhadevi", "Affordable AC maintenance in Prabhadevi",
  "Emergency AC repair in Prabhadevi", "Mahalaxmi air conditioning repair", "AC service in Mahalaxmi",
  "Best AC technicians in Mahalaxmi", "air services in Mahalaxmi", "Affordable AC maintenance in Mahalaxmi",
  "Emergency AC repair in Mahalaxmi", "Lower Parel air conditioning repair", "AC service in Lower Parel",
  "Best AC technicians in Lower Parel", "air services in Lower Parel", "Affordable AC maintenance in Lower Parel",
  "Emergency AC repair in Lower Parel", "Mumbai Central air conditioning repair", "AC service in Mumbai Central",
  "Best AC technicians in Mumbai Central", "air services in Mumbai Central", "Affordable AC maintenance in Mumbai Central",
  "Emergency AC repair in Mumbai Central", "Grant Road air conditioning repair", "AC service in Grant Road",
  "Best AC technicians in Grant Road", "air services in Grant Road", "Affordable AC maintenance in Grant Road",
  "Emergency AC repair in Grant Road", "Churni Road air conditioning repair", "AC service in Churni Road",
  "Best AC technicians in Churni Road", "air services in Churni Road", "Affordable AC maintenance in Churni Road",
  "Emergency AC repair in Churni Road", "Marine Lines air conditioning repair", "AC service in Marine Lines",
  "Best AC technicians in Marine Lines", "air services in Marine Lines", "Affordable AC maintenance in Marine Lines",
  "Emergency AC repair in Marine Lines", "Churchgate air conditioning repair", "AC service in Churchgate",
  "Best AC technicians in Churchgate", "air services in Churchgate", "Affordable AC maintenance in Churchgate",
  "Emergency AC repair in Churchgate", "Affordable AC service near me", "Trusted AC repair services",
  "Professional air conditioning repair", "Certified AC technicians near me", "Licensed HVAC repair services",
  "Reliable air conditioner servicing", "Local AC repair specialists", "HVAC service providers near me",
  "Experienced AC service companies", "Best air conditioner repair near me", "24-hour HVAC repair",
  "Same-day AC service near me", "Rapid AC repair services", "Emergency cooling system repair",
  "Fast AC maintenance near me", "Weekend AC repair service", "Holiday HVAC repair services",
  "24/7 air conditioning repair near me", "AC filter cleaning services", "Affordable AC gas refilling near me",
  "AC coil replacement services", "Deep cleaning for air conditioners", "Air conditioner rust-proofing",
  "Split AC gas refilling cost", "AC gas recharge near me", "Window AC coil cleaning services",
  "Short-term AC rental services", "Seasonal AC rentals near me", "Monthly AC rental plans",
  "Split AC on rent near me", "Budget-friendly AC rental options", "Portable air conditioner hire near me",
  "Corporate AC rental services", "Customized AC AMC plans", "Comprehensive air conditioner AMC",
  "HVAC annual maintenance contract", "Best AMC for air conditioners", "Affordable AMC services near me",
  "Regular AC maintenance packages", "HVAC preventative maintenance", "AMC for central air conditioning systems",
  "AC installation near me", "Air conditioner replacement services", "Split AC installation cost",
  "Affordable window AC setup", "Central AC installation services", "Upgrading old AC units",
  "Summer AC repair deals", "Winter HVAC maintenance", "Pre-summer AC tune-up services",
  "Monsoon-proof AC maintenance", "Off-season air conditioner rentals", "Home AC service packages",
  "Residential air conditioning repair", "Office HVAC maintenance services", "Commercial cooling system repair", 
  "Corporate air conditioner repair contracts", "AC service providers in Mumbai", "HVAC repair near Mumbai", 
  "AC maintenance in Mumbai", "Best AC repair services in Mumbai", "Affordable AC rental in Mumbai", 
  "Why is my AC not cooling?", "How to recharge AC gas?", "What is the cost of AC service?", 
  "Best AC technicians for split AC repair", "Affordable air conditioner tune-up", 
  "Where to find AC gas refill near me?", "How much does HVAC maintenance cost?"
];

const allKeywords = [
  ...packersAndMoversKeywords,
  ...packersAndMoversData.flatMap(state => state.cities.map(city => `Packers and Movers from Mumbai to ${city}`)),
  ...acServiceKeywords,
];

const KeywordsList = () => {
  const [search, setSearch] = useState("");

  const filteredKeywords = allKeywords.filter(keyword =>
    keyword.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="p-4">
      <h2 className="text-xl font-title font-bold mb-2">Keywords List</h2>
      <input
        type="text"
        placeholder="Search keywords..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        className="border p-2 w-full mb-4 rounded"
      />
      <ul className="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-2">
        {filteredKeywords.map((keyword, index) => (
          <li key={index} className="py-1 text-xs font-body hover:underline">{keyword}</li>
        ))}
      </ul>
    </div>
  );
};

export default KeywordsList;